//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssmgas_v._0._1.Vistas
{


    public partial class Contacto
    {
    }
}
